name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t mehaksaini0301/lost-with-mehak:latest .

      - name: Push Docker Image
        run: docker push mehaksaini0301/lost-with-mehak:latest

  deploy:
    needs: docker
    runs-on: self-hosted

    steps:
      - name: Pull latest image
        run: docker pull mehaksaini0301/lost-with-mehak:latest

      - name: Stop old container
        run: docker stop lost-container
        continue-on-error: true

      - name: Remove old container
        run: docker rm lost-container
        continue-on-error: true

      - name: Run new container
        run: docker run -d --name lost-container -p 8081:80 mehaksaini0301/lost-with-mehak:latest